wandb_version: 1

alpha:
  value: 1.2498756317654742
batch_size:
  value: 64
domain_layers:
  value:
  - 16
  - 8
es_min_delta:
  value: 0.001
es_patience:
  value: 5
feature_layers:
  value:
  - 64
  - 16
label_layers:
  value:
  - 16
  - 8
lr:
  value: 0.000839684186376172
num_epochs:
  value: 20
obs:
  value: mags
sims:
  value:
  - TNG50
  - TNG100
  - Eagle100
  - Simba100
  - TNG_ALL
train_sim:
  value:
  - TNG100
  - Eagle100
  - Simba100
  - TNG_ALL
