wandb_version: 1

alpha:
  value: 0.7193093973435559
batch_size:
  value: 64
domain_layers:
  value:
  - 16
  - 8
es_min_delta:
  value: 0.001
es_patience:
  value: 5
feature_layers:
  value:
  - 64
  - 16
label_layers:
  value:
  - 16
  - 8
lr:
  value: 0.0007110110216417612
num_epochs:
  value: 50
obs:
  value: mags_morph
sims:
  value:
  - TNG50
  - TNG100
  - Eagle100
  - Simba100
  - TNG_ALL
train_sim:
  value:
  - TNG50
  - TNG100
  - Simba100
  - TNG_ALL
