wandb_version: 1

alpha:
  value: 0.5678240974154541
batch_size:
  value: 32
domain_layers:
  value:
  - 16
  - 8
es_min_delta:
  value: 0.001
es_patience:
  value: 5
feature_layers:
  value:
  - 64
  - 16
label_layers:
  value:
  - 16
  - 8
lr:
  value: 0.00698173570782652
num_epochs:
  value: 100
obs:
  value: mags_morph_extra
sims:
  value:
  - TNG50
  - TNG100
  - Eagle100
  - Simba100
  - TNG_ALL
train_sim:
  value:
  - TNG50
  - Eagle100
  - Simba100
  - TNG_ALL
